pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }

    stages {
        stage('message'){
            steps{
                sh 'mvn --version'
                sh 'java -version'
            }
        }

        stage('Initialize'){
            steps{
                // echo "PATH = ${M2_HOME}/bin:${PATH}"
                // echo "M2_HOME = /opt/maven"
                bat 'echo PATH = %M2_HOME%\\bin;%PATH%'
                bat 'echo M2_HOME = C:\\Program Files\\Apache\\Maven'
            }
        }
        stage('Build') {
            steps {
                //dir("/var/lib/jenkins/workspace/New_demo/my-app/") it is for linux
                dir("C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\maven_project1\\my-app")  {
                sh 'mvn -B -DskipTests clean package'
                }
            }
        }
     }
    post {
        always {
            echo "Collecting test results..."
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
        }
    }
}
